### ISSUE TITLE
How robust is gdbmi?

### ISSUE THREAD

**Issue by aaronatp** [danielzfranklin/gdbmi#1]
Hey @dzfranklin, I'm developing an application that needs to interface with gdb's MI. I'm pretty new to Rust and don't know all the language's best design practices. I see you are currently developing some popular Rust libraries, including cargo-rr, but I noted that gdbmi hasn't been updated in nearly 3 years. May I ask, is gdbmi's code functional, "good Rust"? In other words, can my application rely on it? Also, newbie question, are there any breaking changes between Rust from 3 years ago and Rust today? Will gdbmi work with modern Rust? For the purposes of my application, it's not a problem that gdbmi isn't actively developed, although I may open a PR at some point along the way if you are still interested in actively developing the library :)

**Comment by dzfranklin** [comment]
Hi. I'm not an experienced rust developer. I built all those libraries while learning Rust. Since then I've gotten other interests and paused my Rust open source development indefinitely. You're welcome to use it if you want but I wouldn't call it functional good code.

**Comment by aaronatp** [comment]
I appreciate you letting me know, thank you.
